// scripts/pages-list.js
exports.pages = [
  { path: "/", priority: "1.0" },
  { path: "/modulo/1", priority: "0.8" },
  { path: "/modulo/2", priority: "0.8" },
  { path: "/modulo/3", priority: "0.8" },
  { path: "/modulo/4", priority: "0.8" },
  { path: "/modulo/5", priority: "0.8" },
  { path: "/modulo/6", priority: "0.8" },
  { path: "/modulo/7", priority: "0.8" },
  { path: "/modulo/8", priority: "0.8" },
  { path: "/modulo/9", priority: "0.8" },
  { path: "/modulo/10", priority: "0.8" },
  { path: "/modulo/11", priority: "0.8" },
  { path: "/modulo/12", priority: "0.8" },
  { path: "/modulo/13", priority: "0.8" },
  { path: "/modulo/14", priority: "0.8" },
  { path: "/modulo/15", priority: "0.8" },
  { path: "/modulo/a", priority: "0.7" },
  { path: "/modulo/b", priority: "0.7" },
  { path: "/modulo/c", priority: "0.7" },
  { path: "/biblioteca", priority: "0.9" },
  { path: "/filme/tangerine-2015", priority: "0.8" },
  { path: "/filme/in-the-mood-for-love", priority: "0.8" },
  { path: "/filme/taxi-tehran", priority: "0.8" },
  { path: "/filme/ma-rosa", priority: "0.8" },
  { path: "/filme/chungking-express", priority: "0.8" },
  { path: "/filme/boy-2019", priority: "0.8" },
  { path: "/filme/ma", priority: "0.8" },
  { path: "/filme/zero-days", priority: "0.8" },
  { path: "/filme/capernaum", priority: "0.8" },
  { path: "/filme/1917", priority: "0.8" },
  { path: "/filme/synonymes", priority: "0.8" },
  { path: "/filme/atlantics", priority: "0.8" },
  { path: "/filme/baby-driver", priority: "0.8" },
  { path: "/filme/whiplash", priority: "0.8" },
  { path: "/filme/roma", priority: "0.8" },
  { path: "/filme/parasite", priority: "0.8" }
  // ... mantenha seus filmes, módulos e outras rotas
];
